config/routes.rb
Rails.application.routes.draw do
  get "/cocktails/all", to: "cocktails#all"
  delete "/cocktails/all", to: "cocktails#allDestroy"

  resources :cocktails do
    resources :doses, except: [:destroy]
  end

  root to: "cocktails#index"


  # get 'dose/create'
  # get 'dose/new'
  # get 'dose/edit'
  # get 'dose/update'
  # get 'dose/show'
  # get 'dose/index'
  resources :doses, only: [:destroy]
  # get 'cocktails/new'
  # get 'cocktails/create'
  # get 'cocktails/index'
  # get 'cocktails/show'
  # get 'cocktails/edit'
  # get 'cocktails/update'
  # get 'cocktails/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  # validates :image, presence: true
  validates :instruction, presence: true
  validates :name, presence:true, allow_blank: false, uniqueness: true
  # mount_uploader :image, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :quantity, presence:true
  # validates :description, presence:true
  validates :cocktail, presence:true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence:true, allow_blank: false, uniqueness: true
  validates :category, presence:true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      respond_to do |format|
        format.html {redirect_to cocktail_path(@cocktail)}
        # format.js {}
      end
    else
     flash[:alert] = "failed"
     render :new
   end
 end

 def all
  @cocktails = Cocktail.all

 end



def index
  @cocktails = Cocktail.all
end

def show
  @cocktail = Cocktail.find(params[:id])
end

def edit
  @cocktail = Cocktail.find(params[:id])
end

def update
  @cocktail = Cocktail.find(params[:id])

  if @cocktail.update(cocktail_params)
    redirect_to @cocktail, notice: 'Article was successfully updated.'
  else
    render :edit
  end
end

def destroy
  @cocktail = Cocktail.find(params[:id])
  @cocktail.destroy

  redirect_to cocktails_path
end

def allDestroy
  @cocktail = Cocktail.find(params[:id])
  @cocktail.destroy

  redirect_to cocktails_path
end






private

def cocktail_params
  params.require(:cocktail).permit(:name, :instruction)
end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.create(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      respond_to do |format|
        format.html {redirect_to cocktail_path(@cocktail)}
        format.js {}
      end
    else
     flash[:alert] = "failed"
     render :new
   end

 end

 def edit
 end

 def update
 end

 def show
 end

 def index
 end

 def destroy
  @dose = Dose.find(params[:id])
  @dose.destroy
end

private

def dose_params
  params.require(:dose).permit(:description, :ingredient_id, :quantity)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/views/cocktails/_form.html.erb
<%= form_for(@cocktail, class: 'form') do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :instruction %>
  <%= f.submit %>
<% end %>

app/views/cocktails/all.html.erb
<h2>All Cocktails</h2>
<hr>


<%  alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");  %>
<% cockail_sorted = @cocktails.sort_by{|cocktail| cocktail.name.capitalize}%>

<% alphabet.each do |letter|  %>
<%i = 0 %>


<% cockail_sorted.each do |cocktail|%>
<% if cocktail.name.first.capitalize == letter  %>
<% i+=1 %>
<% end %>
<% end %>
<% if i == 0 %>
<% alphabet = alphabet - letter.split %>

<% end %>
<% end %>

<div class="container-letters">
  <ul class="list-inline letter-link">
    <% alphabet.each do |letter| %>
    <% if letter != alphabet.last %>


    <a href="#<%= letter %>">
     <li class="list-inline-item "><strong><%= letter %></strong>
     </li></a>|

     <% else %>
     <a href="#<%= letter %>">
      <li class="list-inline-item"><strong><%= letter %></strong>
      </li></a>
      <% end %>
      <% end %>
    </ul>
  </div>
  <div class="container-list">
    <div class="row">


      <div class="col-xs-12 col-sm-12 col-md-6 all-col-1">



        <% alphabet.each_with_index do |letter, index|  %>


        <% if index < alphabet.length / 2 %>

        <a name="<%= letter %>"> <hr></a>
        <div class="circle-letter">
          <%= letter %>
        </div>
        <ul class="list-inline cocktail-list">
          <% cockail_sorted.each do |cocktail|%>

          <% if cocktail.name.first.capitalize == letter  %>

          <li class-"list-inline-item"><h5> <%= link_to cocktail.name.capitalize, cocktail_path(cocktail)%>
                  <small class="text-muted"><%= link_to "", cocktails_all_path(cocktail), :class => "far fa-trash-alt trashcan", :method => :delete, :confirm => "Are you sure ?"%>
          </h5></li><li>|</li>
          <% end %>
          <% end %>
        </ul>
        <% end %>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 all-col-2">
        <% alphabet.each_with_index do |letter, index|  %>


        <% if index >= alphabet.length / 2 %>

        <a name="<%= letter %>"> <hr></a>
        <div class="circle-letter">
          <%= letter %>
        </div>
        <ul class="list-inline cocktail-list">
          <% cockail_sorted.each_with_index do |cocktail, index|%>

          <% if cocktail.name.first.capitalize == letter  %>

          <li class-"list-inline-item"><h5> <%= link_to cocktail.name.capitalize, cocktail_path(cocktail)%></h5></li>
          <li>|</li>


          <% end %>
          <% end %>
        </ul>
        <% end %>
        <% end %>
      </div>






    </div>
  </div>

  <% content_for :js do %>
  <script>

    function removeTabActive(){
      document.querySelectorAll(".tab").forEach(function(element) {
        element.classList.remove("active");
      });
    }
    removeTabActive();
    document.getElementById("tab2").classList.add("active");

  </script>
  <% end %>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

<%= render 'form' %> <%= link_to 'Show', @cocktails %> | <%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<h2>Featured Cocktails</h2>
<hr>
<div class="row">

 <!-- LES 6 CARTES -->


 <% @cocktails.take(6).each do |cocktail| %>
 <% ingredient_sorted = cocktail.ingredients.sort{|a,b| a.category <=> b.category } %>

 <div class="col-12 col-sm-6 col-md-4">
  <div class="card my-card">
    <% if cocktail.image %>
    <div class="card-img-top my-card-image" style="background-image:url('<%= cl_image_path cocktail.image %>')" alt="Card image cap">
      <% else %>
      <div class="card-img-top my-card-image" style="background-image:url('')" alt="Card image cap">
      <% end %>
      <div class="card-linear-gradient">
      </div>
    </div>
    <div class="card-body my-cards-body">
      <h5> <%= link_to cocktail.name.capitalize, cocktail_path(cocktail)%></h5>
      <ul class="list-inline">
        <% ingredient_sorted.each do |x| %>
        <li class="list-inline-item text-muted">
          <% if x.category == "fruit" %>
          <i class="fas fa-lemon category"></i>
          <% elsif x.category == "juice" %>
          <i class="fas fa-tint category" ></i>
          <% elsif x.category == "alcohol" %>
          <i class="fas fa-glass-martini category"></i>
          <% else %>
          <i class="fas fa-leaf category"></i>
          <% end %>
          <%= x.name.capitalize %>
        </li>
        <% end %>
      </ul>
    </div>
    <div class="card-footer my-card-footer">
      <small class="text-muted"><%= link_to "", cocktail_path(cocktail), :class => "far fa-trash-alt trashcan", :method => :delete, :confirm => "Are you sure ?"%>
      </small>
      <small class="text-muted"><%= link_to "", cocktail_path(cocktail), :class => "far fa-edit trashcan"%>
      </small>
    </div>
  </div>
</div>

<% end %>
</div>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>

<%= render 'form', cocktail: @cocktail %>

  <% content_for :js do %>
  <script>

    function removeTabActive(){
      document.querySelectorAll(".tab").forEach(function(element) {
        element.classList.remove("active");
      });
    }
    removeTabActive();
    document.getElementById("tab3").classList.add("active");

  </script>
 <% end %>

app/views/cocktails/show.html.erb
<h2><%= @cocktail.name.capitalize %> <%= link_to "", edit_cocktail_path(@cocktail[:id]), :class => "far fa-edit trashcan edit-button" %></h2>

<hr>

<div class="row">
  <div class="col-xs-12 col-md-6">
    <%= cl_image_tag(@cocktail.image, :alt => @cocktail.name, :class => "image-show")%>
  </div>
  <div class="col-xs-12 col-md-6 container-ingredients">

     <% ingredients_array = []  %>
     <% alcohol = false  %>
     <% fruit = false  %>
     <% juice = false  %>
     <% spice = false  %>


    <% @cocktail.doses.each do |dose| %>

    <% ingredients_array .push [dose.quantity, dose.ingredient.name, dose.ingredient.category, dose] %>
    <% end %>

    <% ingredients_array.each do |ingredient| %>
      <% if ingredient.include?("alcohol") %>
        <% alcohol = true %>
      <% end %>
      <% if ingredient.include?("juice") %>
        <% juice = true %>
      <% end %>
      <% if ingredient.include?("spice") %>
        <% spice = true %>
      <% end %>
      <% if ingredient.include?("fruit") %>
        <% fruit = true %>
      <% end %>
    <% end %>

    <% if alcohol %>
    <p>Alcohol</p>
    <% end %>
      <% ingredients_array.each do |ingredient| %>
        <% if ingredient[2] == "alcohol" %>
          <h5 data-dose-id="<%= ingredient[3].id %>"><%=  ingredient[0] %> of <%=  ingredient[1].capitalize %>
          <%= link_to "", dose_path(ingredient[3]), :method => :delete, remote: true, :class => "far fa-trash-alt trashcan-show trashcan"%></h5>
        <% end %>
      <% end %>

    <% if juice %>
     <hr><p>Mixer</p>
    <% end %>

      <% ingredients_array.each do |ingredient| %>
        <% if ingredient[2] == "juice" %>
                  <h5 data-dose-id="<%= ingredient[3].id %>"><%=  ingredient[0] %> of <%=  ingredient[1].capitalize %>
          <%= link_to "", dose_path(ingredient[3]), :method => :delete, remote: true, :class => "far fa-trash-alt trashcan-show trashcan"%></h5>
        <% end %>
      <% end %>

 <% if fruit %>
     <hr><p>Food items</p>
    <% end %>

      <% ingredients_array.each do |ingredient| %>
        <% if ingredient[2] == "fruit" %>
          <h5 data-dose-id="<%= ingredient[3].id %>"><%=  ingredient[0] %> of <%=  ingredient[1].capitalize %>
          <%= link_to "", dose_path(ingredient[3]), :method => :delete, remote: true,  :class => "far fa-trash-alt trashcan-show trashcan"%></h5>
        <% end %>
      <% end %>

      <% if spice %>
     <hr><p>Spices</p>
    <% end %>

      <% ingredients_array.each do |ingredient| %>
        <% if ingredient[2] == "spice" %>
          <h5 data-dose-id="<%= ingredient[3].id %>"><%=  ingredient[0] %> of <%=  ingredient[1].capitalize %>
          <%= link_to "", dose_path(ingredient[3]), :method => :delete, remote: true,  :class => "far fa-trash-alt trashcan-show trashcan"%></h5>
        <% end %>
      <% end %>
      <hr class="last-hr">
<%= link_to "+ Add ingredient", new_cocktail_dose_path(@cocktail[:id]), :class => "trashcan add-ingredient" %>

       </div>

</div>
      <hr>
<div class = "col-xs-12 container-ingredients">

      <p>How to make a <%= @cocktail.name.capitalize %>:</p>
      <% instruction_array = @cocktail.instruction.split(".")%>
      <h5 class="show-instruction"> <ul><% instruction_array.each do |instruction| %>
       <li> <%= instruction %></li>
        <% end %>
        <li> <%= link_to "", edit_cocktail_path(@cocktail[:id]), :class => "far fa-edit trashcan edit-button-2" %></li>
      </ul> </h5>


</div>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/_form.html.erb
<% ingredients = Ingredient.all %>
<% ing_alcohol = ingredients.where(category: "alcohol").order(:name)%>
<% ing_fruit = ingredients.where(category: "fruit").order(:name)%>
<% ing_juice = ingredients.where(category: "juice").order(:name)%>
<% ing_spice = ingredients.where(category: "spice").order(:name)%>
<% dose = [ "0.5 oz", "1 oz", "1.5 oz", "2 oz", "2.5 oz", "3 oz", "3.5 oz", "4 oz","4.5 oz", "5 oz", "10 oz", "15 oz", "20 oz"]  %>



	<div class="form-class display-none" id="alcohol-form">
		<% ing_alcohol.name.capitalize! %>



		<%= form_for [@cocktail, @dose], {class: 'form'} do |f| %>
		<%= f.collection_select :ingredient_id, ing_alcohol, :id, :name, {:include_blank => 'Choice of alcohols'}, :class => "form-control my-form-control", :id => "select-alcohol"%>
		<%= f.select :quantity, options_for_select(dose), {}, { :class => "form-control my-form-control" } %>
		<%= f.submit 'Add ingredient ', :class => 'form-control my-form-btn' %>
		<% end %>
	</div>

	<div class="form-class display-none" id="food-form">
		<% ing_fruit.name.capitalize! %>
		<%= form_for [@cocktail, @dose] do |f| %>
		<%= f.collection_select :ingredient_id, ing_fruit, :id, :name, {:include_blank => 'Choice of food items'}, :class => "form-control my-form-control" %>
		<%= text_field :dose, :quantity, :placeholder => "Quantity", :class => "form-control my-form-control" %>
		<%= f.submit 'Add ingredient ', :class => 'form-control my-form-btn' %>
		<% end %>
	</div>

	<div class="form-class display-none" id="mixer-form">
		<% ing_juice.name.capitalize! %>
		<%= form_for [@cocktail, @dose] do |f| %>
		<%= f.collection_select :ingredient_id, ing_juice, :id, :name, {:include_blank => 'Choice of mixers'}, :class => "form-control my-form-control" %>
		<%= f.select :quantity, options_for_select(dose), {}, { :class => "form-control my-form-control" } %>
		<%= f.submit 'Add ingredient ', :class => 'form-control my-form-btn' %>
		<% end %>
	</div>



		<div class="form-class display-none" id="spice-form">
			<% ing_spice.name.capitalize! %>
			<%= form_for [@cocktail, @dose] do |f| %>
			<%= f.collection_select :ingredient_id, ing_spice, :id, :name, {:include_blank => 'Choice of spices'}, :class => "form-control my-form-control" %>
			<%= text_field :dose, :quantity, :placeholder => "Quantity", :class => "form-control my-form-control" %>
			<%= f.submit 'Add ingredient ', :class => 'form-control my-form-btn' %>
			<% end %>

			</div>

app/views/doses/create.html.erb
<h1>Dose#create</h1>
<p>Find me in app/views/dose/create.html.erb</p>

app/views/doses/create.js.erb
alert("test")
// function refreshForm(innerHTML) {
//   const newIngForm = document.getElementById('new_review');
//   newIngForm.innerHTML = innerHTML;
// }
// console.log("test")
// function addReview(doseHTML) {
//   const addedIngredient = document.getElementById('addedIngredient');
//   addedIngredient.insertAdjacentHTML('beforeend', doseHTML);
// }

//   addReview('<%= j render "doses/new", dose: @dose %>');

app/views/doses/destroy.html.erb
<h1>Dose#destroy</h1>
<p>Find me in app/views/dose/destroy.html.erb</p>

app/views/doses/destroy.js.erb
document.querySelector("[data-dose-id='<%= @dose.id %>']").remove();

app/views/doses/edit.html.erb
<h1>Dose#edit</h1>
<p>Find me in app/views/dose/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Dose#index</h1>
<p>Find me in app/views/dose/index.html.erb</p>

app/views/doses/new.html.erb
<h2><%= @cocktail.name.capitalize %></h2>
<div class="ingredients-already-there">
 <% ingredient_sorted = @cocktail.ingredients.sort{|a,b| a.category <=> b.category } %>
 <div id="addedIngredient"></div>

 <ul class="list-inline"> <small>
  <% ingredient_sorted.each do |x| %>
  <li class="list-inline-item text-muted icon-list">
    <% if x.category == "fruit" %>
    <i class="fas fa-lemon category"></i>
    <% elsif x.category == "juice" %>
    <i class="fas fa-tint category"></i>
    <% elsif x.category == "alcohol" %>
    <i class="fas fa-glass-martini category"></i>
    <% else %>
    <i class="fas fa-leaf category"></i>
    <% end %>
    <%= x.name.capitalize%>
  </li>
  <% end %>
</small></ul>
</div>
<hr>

<div class="form-container">

  <h5>Add an ingredient to <%= @cocktail.name.capitalize %></h5>

  <div id="new-ingredient-container">
    <button class="btn btn-form-display" id="alcohol-btn" value="Alcohol"><i class="fas fa-glass-martini category"></i><p class="very-small">Alcohol</p></button>

    <button class="btn btn-form-display" id="juice-btn" value="Mixer"><i class="fas fa-tint category"></i><p class="very-small">Mixer</p></button>
    <button class="btn btn-form-display" id="food-btn" value="Food"><i class="fas fa-lemon category"></i><p class="very-small">Food</p></button>
    <button class="btn btn-form-display" id="spice-btn" value="Spice"><i class="fas fa-leaf category"></i><p class="very-small">Spice</p></button>
  </div>
  <hr>

  <div class="my-form-ingredients">
    <%= render 'form', dose: @dose, cocktail: @cocktail%>
  </div>

  <% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <hr>

  <div id="saq-query" class="row saq-box"></div>
</div>

app/views/doses/show.html.erb
<h1>Dose#show</h1>
<p>Find me in app/views/dose/show.html.erb</p>

app/views/doses/update.html.erb
<h1>Dose#update</h1>
<p>Find me in app/views/dose/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div class="navbar-wagon">
    <!-- Logo -->

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
      <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
      <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>
      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Host</a></li>
          <li><a href="#">Trips</a></li>
          <li><a href="#">Messagese</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="my-header banner">
    <div class="banner-content">
      <h1 id="my-title">Mister Cocktails</h1>
      <p>Learn to code with us in Berlin</p>
      <!-- <a class="btn btn-primary btn-lg"></a> -->
    </div>
  </div>
  <a name="anchor-tabs"></a>


  <!-- tout ce qui est en dessous de la banner -->
  <div class="row main-container">

    <!-- SECTION DE GAUCHE -->
    <div class="my-container col-xs-12 col-sm-6 col-md-8 col-lg-9 my-dropdown-container" >

      <!-- TABS QUI PRENNTENT TOUTES LA LONGUEUR -->
      <div class="list-tabs">

        <div class="tabs">
          <%= link_to "Featured", cocktails_path(:anchor => "anchor-tabs"), :class => "tab active", :id => "tab1"%>
          <%= link_to "All cocktails",  cocktails_all_path(:anchor => "anchor-tabs"), :class => "tab", :id => "tab2"%>
          <%= link_to "Create a cocktail", new_cocktail_path(:anchor => "anchor-tabs"), :class => "tab", :id => "tab3"%>
        </div>

      </div>

      <div class="container-yield" style="padding:3%;">
        <!-- CONTENEUR QUI VA REMPLIR TOUT LE RESTE -->
        <%= yield %>

      </div>
    </div>

    <!-- SECTION DE DROITE -->
    <div class="left-bar col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <div class="left-bar-after">
      </div>
      <div class="left-bar-after2">
        <h3>About cocktail!</h3>
        <p>
          The first "cocktail party" ever thrown was allegedly by Mrs. Julius S. Walsh Jr. of St. Louis, Missouri, in May 1917. Mrs. Walsh invited 50 guests to her home at noon on a Sunday. The party lasted an hour, until lunch was served at 1 pm. The site of this first cocktail party still stands. In 1924, the Roman Catholic Archdiocese of St. Louis bought the Walsh mansion at 4510 Lindell Boulevard, and it has served as the local archbishop's residence ever since.
        </p><p>
          During Prohibition in the United States (1919–1933), when alcoholic beverages were illegal, cocktails were still consumed illegally in establishments known as speakeasies. The quality of liquor available during Prohibition was much worse than previously. There was a shift from whiskey to gin, which does not require aging and is therefore easier to produce illicitly. Honey, fruit juices, and other flavorings served to mask the foul taste of the inferior liquors. Sweet cocktails were easier to drink quickly, an important consideration when the establishment might be raided at any moment.
          <br><br>
          <i>Source: Wikipedia</i>
        </p>

      </div>
    </div>

    <div class="my-container-below row">
      <div class="right-bar col-12 col-md-4 col-lg-3">
        <h3>The Party Begins</h3>
        <p>
          The Gilded Age was the golden era of the cocktail. At the turn of the twentieth century, affluent Americans frequented elegant hotels, bars, and restaurants; champagne cocktails were among their favorite drinks.
        </p><p>
          Talented bartenders knew how to make hundreds of cocktails—from the Adonis to the Zaza—and came up with new ones at will. They created and named drinks for regular patrons, news events, cities, and celebrities, and mixed them with great flair. Jerry Thomas was famous for his "Blue Blazer," a mixture of whiskey and boiling water, which he set ablaze and tossed back and forth between two silver-plated mugs. He said it looked like a "stream of liquid fire."
          <br><br>
          <i>Source: Encyclopedia.com</i>
        </p>
      </div>
      <div class="my-container2 col-12 col-md-8 col-lg-9">
      </div>
    </div>

  </div>

  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github" aria-hidden="true"></i></a>
      <a href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a>
    </div>
    <div class="footer-copyright">
      Copyright 2018 <i class="fa fa-copyright" aria-hidden="true"></i> David Poisson Paré
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= javascript_pack_tag 'application' %>
  <%= yield :js %>
</body>

</html>